sudo: required
language: node
services:
  - docker

before_install:
  - docker build -t izhal/react-test -f ./client/Dockerfile.dev ./client
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - heroku auth:token

script:
  - docker run izhal/react-test npm run coverage

after_success:
  - docker build -t izhal/multi-client ./client
  - docker build -t izhal/multi-nginx ./nginx
  - docker build -t izhal/multi-server ./server
  - docker build -t izhal/multi-worker ./worker
  # login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push izhal/multi-client
  - docker push izhal/multi-nginx
  - docker push izhal/multi-server
  - docker push izhal/multi-worker

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: multi-docker27
  on:
    repo: izhal27/multi-docker