sudo: required
services:
  - docker

before_install:
  - docker build -t izhal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run izhal/react-test npm run coverage

after_success:
  - docker build -t izha/multi-client ./client
  - docker build -t izha/multi-nginx ./nginx
  - docker build -t izha/multi-server ./server
  - docker build -t izha/multi-worker ./worker
  # login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push izhal/multi-client
  - docker push izhal/multi-nginx
  - docker push izhal/multi-server
  - docker push izhal/multi-worker
